apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-tier2
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-tier2-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
