apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier2-nfs-client-provisioner
  labels:
    app: tier2-nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tier2-nfs-client-provisioner
  template:
    metadata:
      labels:
        app: tier2-nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-tier2-external-provisioner
            - name: NFS_SERVER
              value: 172.16.1.254
            - name: NFS_PATH
              value: /mnt/nfs/tier2
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.16.1.254
            path: /mnt/nfs/tier2
